###
POST  http://localhost:8080/register
Content-Type: application/json

{
    "Name":"marcos",
    "Email":"marcosfrancomarinho123@4gmail.com",
    "Password":"@1S23478885"
}

###
POST  http://localhost:8080/login
Content-Type: application/json 

{
    "Email":"marcosfrancomarinho123@4gmail.com",
    "Password":"@1S23478885"
}

###
POST  http://localhost:8080/product
Content-Type: application/json
Token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwY2JlMDI4ZC1jMjZkLTRmZDUtYTk4Zi00ODgxMTVmMTJiMzEiLCJleHAiOjE3NTIzODA0NzB9.2p6_uKhbnTgkdwbhVLLED79wc_iQo8708Xno7IfMu6o

{
    "Name":"celular",
    "Price":2555.99,
    "Quantity":2
}